import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/tutor_profile.dart';
import '../models/booking.dart';
import '../models/review.dart';


class TutorService {
  final _db = FirebaseFirestore.instance;
  String get _uid => FirebaseAuth.instance.currentUser!.uid;

  // ---------- 1. ROLE MANAGEMENT ----------
  Future<void> setRole(String role) async {
    await _db.collection('users').doc(_uid).set(
      {'role': role, 'createdAt': FieldValue.serverTimestamp()},
      SetOptions(merge: true),
    );
  }

  // ---------- 2. TUTOR PROFILE CRUD ----------
  Future<void> createOrUpdateProfile(TutorProfile profile) async {
    await _db.collection('tutors').doc(_uid).set(
          profile.toMap(),
          SetOptions(merge: true),
        );
  }

  Stream<TutorProfile?> watchOwnProfile() {
    return _db.collection('tutors').doc(_uid).snapshots().map(
          (doc) => doc.exists ? TutorProfile.fromMap(doc.id, doc.data()!) : null,
        );
  }

  Future<void> deleteProfile() => _db.collection('tutors').doc(_uid).delete();

  // ---------- 3. BOOKING BACKEND (with double-booking prevention) ----------
  /// Runs as a transaction: fails if this tutor already has a booking
  /// at the same date+time that is pending/accepted.
  Future<void> respondToBooking({
    required String bookingId,
    required bool accept,
    String tutorMessage = '',
  }) async {
    final ref = _db.collection('bookings').doc(bookingId);

    await _db.runTransaction((tx) async {
      final snap = await tx.get(ref);
      if (!snap.exists) throw Exception('Booking not found');
      final data = snap.data()!;

      if (accept) {
        final date = data['date'] as Timestamp;
        final time = data['time'] as String;

        // Double-booking check: any other accepted booking, same slot
        final clash = await _db
            .collection('bookings')
            .where('tutorId', isEqualTo: _uid)
            .where('date', isEqualTo: date)
            .where('time', isEqualTo: time)
            .where('status', isEqualTo: 'accepted')
            .get();

        if (clash.docs.isNotEmpty) {
          throw Exception('You already have a session at this time.');
        }

        tx.update(ref, {
          'status': 'accepted',
          'tutorMessage': tutorMessage,
        });

        // Monthly session -> auto-create the recurring entries now,
        // so the student/tutor never has to book each one manually.
        if (data['sessionType'] == 'monthly') {
          await _generateMonthlyOccurrences(bookingId, data);
        }
      } else {
        tx.update(ref, {'status': 'declined', 'tutorMessage': tutorMessage});
      }
    });
  }

  Future<void> _generateMonthlyOccurrences(
      String parentId, Map<String, dynamic> data) async {
    final batch = _db.batch();
    final startDate = (data['date'] as Timestamp).toDate();
    for (int i = 1; i <= 4; i++) {
      final occurrenceDate = startDate.add(Duration(days: 7 * i));
      final ref = _db.collection('bookings').doc();
      batch.set(ref, {
        ...data,
        'status': 'accepted',
        'date': Timestamp.fromDate(occurrenceDate),
        'parentBookingId': parentId,
        'isAutoGenerated': true,
      });
    }
    await batch.commit();
  }

  // ---------- 4. TUTOR SESSIONS (Upcoming / Accept / Decline) ----------
  Stream<List<Booking>> watchIncomingRequests() {
    return _db
        .collection('bookings')
        .where('tutorId', isEqualTo: _uid)
        .where('status', isEqualTo: 'pending')
        .orderBy('date')
        .snapshots()
        .map((q) => q.docs.map(Booking.fromDoc).toList());
  }

  Stream<List<Booking>> watchUpcomingSessions() {
    return _db
        .collection('bookings')
        .where('tutorId', isEqualTo: _uid)
        .where('status', isEqualTo: 'accepted')
        .orderBy('date')
        .snapshots()
        .map((q) => q.docs.map(Booking.fromDoc).toList());
  }

  Stream<List<Booking>> watchSessionHistory() {
    return _db
        .collection('bookings')
        .where('tutorId', isEqualTo: _uid)
        .where('status', whereIn: ['completed', 'declined', 'cancelled'])
        .orderBy('date', descending: true)
        .snapshots()
        .map((q) => q.docs.map(Booking.fromDoc).toList());
  }

  // ---------- 5. FEEDBACK (tutor reads reviews written by students) ----------
  Stream<List<Review>> watchMyReviews() {
    return _db
        .collection('reviews')
        .where('tutorId', isEqualTo: _uid)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((q) => q.docs.map(Review.fromDoc).toList());
  }

  // ---------- 6. TRANSACTION & PAYMENT ----------
  /// Marks a booking Paid AND creates the linked financial record,
  /// exactly as the chart specifies: "Mark Paid + Create Transactions,
  /// setting session to 'Paid' -> Linked financial record".
  Future<void> markSessionPaid({
    required String bookingId,
    required String studentId,
    required double amount,
  }) async {
    final bookingRef = _db.collection('bookings').doc(bookingId);
    final txnRef = _db.collection('transactions').doc();

    final batch = _db.batch();
    batch.update(bookingRef, {'isPaid': true, 'status': 'completed'});
    batch.set(txnRef, {
      'bookingId': bookingId,
      'tutorId': _uid,
      'studentId': studentId,
      'amount': amount,
      'status': 'paid',
      'createdAt': FieldValue.serverTimestamp(),
    });
    await batch.commit();
  }
}