import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/tutor_profile.dart';
import '../models/booking.dart';
import '../models/review.dart';

class TutorService {
  final _db = FirebaseFirestore.instance;
  String get _uid => FirebaseAuth.instance.currentUser!.uid;

  // ---------- 1. ROLE MANAGEMENT ----------
  Future<void> setRole(String role) async {
    await _db.collection('users').doc(_uid).set({
      'role': role,
      'createdAt': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));
  }

  // ---------- 2. TUTOR PROFILE CRUD ----------
  Future<void> createOrUpdateProfile(TutorProfile profile) async {
    await _db
        .collection('tutors')
        .doc(_uid)
        .set(profile.toMap(), SetOptions(merge: true));
  }

  Stream<TutorProfile?> watchOwnProfile() {
    return _db
        .collection('tutors')
        .doc(_uid)
        .snapshots()
        .map(
          (doc) =>
              doc.exists ? TutorProfile.fromMap(doc.id, doc.data()!) : null,
        );
  }

  Future<void> deleteProfile() => _db.collection('tutors').doc(_uid).delete();

  // ---------- 3. BOOKING BACKEND (with double-booking prevention) ----------
  /// Runs as a transaction: fails if this tutor already has a booking
  /// at the same date+time that is pending/accepted.
  Future<void> respondToBooking({
    required String bookingId,
    required bool accept,
    String tutorMessage = '',
  }) async {
    final ref = _db.collection('bookings').doc(bookingId);

    await _db.runTransaction((tx) async {
      final snap = await tx.get(ref);
      if (!snap.exists) throw Exception('Booking not found');
      final data = snap.data()!;

      if (accept) {
        final date = data['date'] as Timestamp;
        final time = data['time'] as String;

        // Double-booking check: any other accepted booking, same slot
        final clash = await _db
            .collection('bookings')
            .where('tutorId', isEqualTo: _uid)
            .where('date', isEqualTo: date)
            .where('time', isEqualTo: time)
            .where('status', isEqualTo: 'accepted')
            .get();

        if (clash.docs.isNotEmpty) {
          throw Exception('You already have a session at this time.');
        }

        tx.update(ref, {'status': 'accepted', 'tutorMessage': tutorMessage});

        // Monthly session -> auto-create the recurring entries now,
        // so the student/tutor never has to book each one manually.
        if (data['sessionType'] == 'monthly') {
          await _generateMonthlyOccurrences(bookingId, data);
        }
      } else {
        tx.update(ref, {'status': 'declined', 'tutorMessage': tutorMessage});
      }
    });
  }

  Future<void> _generateMonthlyOccurrences(
  String parentId,
  Map<String, dynamic> data,
) async {
  final batch = _db.batch();
  final startDate = (data['date'] as Timestamp).toDate();

  // The original booking is Session 1.
  // Create only Sessions 2, 3 and 4.
  for (int i = 1; i <= 3; i++) {
    final occurrenceDate = startDate.add(
      Duration(days: 7 * i),
    );

    final ref = _db.collection('bookings').doc();

    batch.set(ref, {
      ...data,
      'status': 'accepted',
      'date': Timestamp.fromDate(occurrenceDate),
      'parentBookingId': parentId,
      'isAutoGenerated': true,
      'sessionNumber': i + 1,
    });
  }

  await batch.commit();

  // Mark the original booking as Session 1.
    // Original booking = Session 1
  await _db.collection('bookings').doc(parentId).update({
    'sessionNumber': 1,
    'sessionsExpected': 4,
    'sessionsCompleted': 0,
  });
}

  // ---------- 4. TUTOR SESSIONS (Upcoming / Accept / Decline) ----------
  Stream<List<Booking>> watchIncomingRequests() {
    return _db
        .collection('bookings')
        .where('tutorId', isEqualTo: _uid)
        .where('status', isEqualTo: 'pending')
        .orderBy('date')
        .snapshots()
        .map((q) => q.docs.map(Booking.fromDoc).toList());
  }

  Stream<List<Booking>> watchUpcomingSessions() {
    return _db
        .collection('bookings')
        .where('tutorId', isEqualTo: _uid)
        .where('status', isEqualTo: 'accepted')
        .orderBy('date')
        .snapshots()
        .map((q) => q.docs.map(Booking.fromDoc).toList());
  }

  Stream<List<Booking>> watchSessionHistory() {
    return _db
        .collection('bookings')
        .where('tutorId', isEqualTo: _uid)
        .where('status', whereIn: ['completed', 'declined', 'cancelled'])
        .orderBy('date', descending: true)
        .snapshots()
        .map((q) => q.docs.map(Booking.fromDoc).toList());
  }

  // ---------- 5. FEEDBACK (tutor reads reviews written by students) ----------
  Stream<List<Review>> watchMyReviews() {
    return _db
        .collection('reviews')
        .where('tutorId', isEqualTo: _uid)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((q) => q.docs.map(Review.fromDoc).toList());
  }

  // ----------6. MARK SESSION COMPLETED ----------
  // ---------- 6. MARK SESSION COMPLETED + RECORD EARNING ----------
Future<void> markSessionCompleted({
  required String bookingId,
}) async {
  final bookingRef = _db.collection('bookings').doc(bookingId);

  await _db.runTransaction((transaction) async {
    // ------------------------------------------------------------
    // 1. READ BOOKING
    // ------------------------------------------------------------
    final bookingSnap = await transaction.get(bookingRef);

    if (!bookingSnap.exists) {
      throw Exception('Booking not found.');
    }

    final bookingData = bookingSnap.data()!;

    final currentStatus = bookingData['status'] ?? '';

    if (currentStatus == 'completed') {
      throw Exception('This session is already completed.');
    }

    if (currentStatus != 'accepted') {
      throw Exception(
        'Only an accepted session can be marked as completed.',
      );
    }

    final paymentType = bookingData['paymentType'] ?? 'none';
    final amount = (bookingData['amount'] ?? 0).toDouble();

    // ------------------------------------------------------------
    // 2. READ CONTRACT BEFORE WRITING
    // ------------------------------------------------------------
    final contractId = bookingData['contractId'] as String?;

    DocumentSnapshot<Map<String, dynamic>>? contractSnap;

    if (contractId != null && contractId.isNotEmpty) {
      final contractRef =
          _db.collection('contracts').doc(contractId);

      contractSnap = await transaction.get(contractRef);
    }

    // ------------------------------------------------------------
    // 3. MARK BOOKING COMPLETED
    // ------------------------------------------------------------
    final bookingUpdate = <String, dynamic>{
      'status': 'completed',
    };

    // Only mark payment as paid if payment terms exist.
    if (paymentType != PaymentType.none.name && amount > 0) {
      bookingUpdate['paymentStatus'] =
          PaymentStatus.paid.name;
    }

    transaction.update(bookingRef, bookingUpdate);

    // ------------------------------------------------------------
    // 4. NO PAYMENT TERMS
    // ------------------------------------------------------------
    if (paymentType == PaymentType.none.name || amount <= 0) {
      return;
    }

    // ------------------------------------------------------------
    // 5. CREATE EARNING TRANSACTION
    // ------------------------------------------------------------
    final earningRef =
        _db.collection('transactions').doc();

    transaction.set(earningRef, {
      'bookingId': bookingId,
      'contractId': contractId,
      'studentId': bookingData['studentId'],
      'tutorId': bookingData['tutorId'],
      'subject': bookingData['subject'],

      'amount': amount,

      'paymentType': paymentType,

      'status': 'paid',

      'createdAt': FieldValue.serverTimestamp(),
    });

    // ------------------------------------------------------------
    // 6. UPDATE MONTHLY CONTRACT
    // ------------------------------------------------------------
    if (contractId != null &&
        contractId.isNotEmpty &&
        contractSnap != null &&
        contractSnap.exists) {
      final contractRef =
          _db.collection('contracts').doc(contractId);

      final contractData = contractSnap.data()!;

      final completed =
          (contractData['sessionsCompleted'] ?? 0) as int;

      final expected =
          (contractData['sessionsExpected'] ?? 4) as int;

      final newCompleted = completed + 1;

      transaction.update(contractRef, {
        'sessionsCompleted': newCompleted,
        'updatedAt': FieldValue.serverTimestamp(),

        'status': newCompleted >= expected
            ? 'completed'
            : 'active',
      });
    }
  });
}
Future<void> setPaymentTerms({
  required String bookingId,
  required PaymentType paymentType,
  required double amount,
}) async {
  if (amount <= 0) {
    throw Exception('Payment amount must be greater than 0.');
  }

  final bookingRef = _db.collection('bookings').doc(bookingId);
  final bookingSnap = await bookingRef.get();

  if (!bookingSnap.exists) {
    throw Exception('Booking not found.');
  }

  final bookingData = bookingSnap.data()!;

  // ============================================================
  // PER SESSION PAYMENT
  // ============================================================
  if (paymentType == PaymentType.perSession) {
    await bookingRef.update({
      'paymentType': PaymentType.perSession.name,
      'paymentStatus': PaymentStatus.pending.name,
      'amount': amount,

      'sessionsExpected': 1,
      'sessionsCompleted': 0,

      'contractId': null,
      'contractStartDate': null,
      'contractEndDate': null,
    });

    return;
  }

  // ============================================================
  // MONTHLY CONTRACT
  // ============================================================
  if (paymentType == PaymentType.monthlyContract) {
    // If the tutor opens Session 2/3/4 and adds payment terms,
    // find the original Session 1.
    final parentBookingId =
        bookingData['parentBookingId'] ?? bookingId;

    final parentRef =
        _db.collection('bookings').doc(parentBookingId);

    final parentSnap = await parentRef.get();

    if (!parentSnap.exists) {
      throw Exception('Original booking for this contract was not found.');
    }

    final parentData = parentSnap.data()!;

    final startDate =
        (parentData['date'] as Timestamp).toDate();

    final endDate = startDate.add(
      const Duration(days: 28),
    );

    // ------------------------------------------------------------
    // Get all sessions belonging to this contract
    // ------------------------------------------------------------

    final generatedSessions = await _db
        .collection('bookings')
        .where(
          'parentBookingId',
          isEqualTo: parentBookingId,
        )
        .get();

    final sessionRefs = <DocumentReference>[
      parentRef,
      ...generatedSessions.docs.map((doc) => doc.reference),
    ];

    // Make sure we have exactly the expected four sessions.
    if (sessionRefs.length < 4) {
      throw Exception(
        'Monthly sessions are not ready yet. '
        'Please make sure the four sessions have been created.',
      );
    }

    // ------------------------------------------------------------
    // Create or reuse contract
    // ------------------------------------------------------------

    final existingContractId =
        parentData['contractId'] as String?;

    final contractRef = existingContractId != null &&
            existingContractId.isNotEmpty
        ? _db.collection('contracts').doc(existingContractId)
        : _db.collection('contracts').doc();

    final contractId = contractRef.id;

    // Monthly contract amount is the TOTAL contract amount.
    final totalContractAmount = amount;

    // Current design = 4 sessions per monthly contract.
    const sessionsExpected = 4;

    final amountPerSession =
        totalContractAmount / sessionsExpected;

    final batch = _db.batch();

    // ------------------------------------------------------------
    // Save contract
    // ------------------------------------------------------------

    batch.set(
      contractRef,
      {
        'studentId': parentData['studentId'],
        'tutorId': parentData['tutorId'],
        'subject': parentData['subject'],

        'paymentType': PaymentType.monthlyContract.name,

        // Total amount agreed for the contract
        'totalAmount': totalContractAmount,

        // Amount attributed to each completed session
        'amountPerSession': amountPerSession,

        'sessionsExpected': sessionsExpected,
        'sessionsCompleted': 0,

        'startDate': Timestamp.fromDate(startDate),
        'endDate': Timestamp.fromDate(endDate),

        'status': 'active',

        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      SetOptions(merge: true),
    );

    // ------------------------------------------------------------
    // Update all sessions
    // ------------------------------------------------------------

    for (final sessionRef in sessionRefs) {
      final sessionSnap = await sessionRef.get();

      if (!sessionSnap.exists) {
        continue;
      }

      final sessionData =
          sessionSnap.data() as Map<String, dynamic>;

      final sessionNumber =
          sessionData['sessionNumber'] ?? 1;

      batch.update(
        sessionRef,
        {
          'paymentType':
              PaymentType.monthlyContract.name,

          'paymentStatus':
              PaymentStatus.pending.name,

          // IMPORTANT:
          // Each session gets its share of the contract,
          // not the entire contract amount.
          'amount': amountPerSession,

          'contractId': contractId,

          'sessionsExpected': sessionsExpected,

          'contractStartDate':
              Timestamp.fromDate(startDate),

          'contractEndDate':
              Timestamp.fromDate(endDate),

          'sessionNumber': sessionNumber,
        },
      );
    }

    await batch.commit();
  }
}
}