import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/tutor_profile.dart';
import '../models/booking.dart';
import '../models/review.dart';

class TutorService {
  final _db = FirebaseFirestore.instance;
  String get _uid => FirebaseAuth.instance.currentUser!.uid;

  // ---------- 1. ROLE MANAGEMENT ----------
  Future<void> setRole(String role) async {
    await _db.collection('users').doc(_uid).set({
      'role': role,
      'createdAt': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));
  }

  // ---------- 2. TUTOR PROFILE CRUD ----------
  Future<void> createOrUpdateProfile(TutorProfile profile) async {
    await _db
        .collection('tutors')
        .doc(_uid)
        .set(profile.toMap(), SetOptions(merge: true));
  }

  Stream<TutorProfile?> watchOwnProfile() {
    return _db
        .collection('tutors')
        .doc(_uid)
        .snapshots()
        .map(
          (doc) =>
              doc.exists ? TutorProfile.fromMap(doc.id, doc.data()!) : null,
        );
  }

  Future<void> deleteProfile() => _db.collection('tutors').doc(_uid).delete();

  // ---------- 3. BOOKING BACKEND ----------
  Future<void> respondToBooking({
    required String bookingId,
    required bool accept,
    String tutorMessage = '',
  }) async {
    final ref = _db.collection('bookings').doc(bookingId);
    final snap = await ref.get();

    if (!snap.exists) throw Exception('Booking not found');
    final data = snap.data()!;

    if (accept) {
      final date = data['date'] as Timestamp;
      final time = data['time'] as String;

      // Check double-booking
      final clash = await _db
          .collection('bookings')
          .where('tutorId', isEqualTo: _uid)
          .where('date', isEqualTo: date)
          .where('time', isEqualTo: time)
          .where('status', isEqualTo: 'accepted')
          .get();

      if (clash.docs.isNotEmpty) {
        throw Exception('You already have a session at this time.');
      }

      await ref.update({
        'status': 'accepted',
        'tutorMessage': tutorMessage,
      });

      if (data['sessionType'] == 'monthly') {
        await _generateMonthlyOccurrences(bookingId, data);
      }
    } else {
      await ref.update({
        'status': 'declined',
        'tutorMessage': tutorMessage,
      });
    }
  }

  Future<void> _generateMonthlyOccurrences(
    String parentId,
    Map<String, dynamic> data,
  ) async {
    final batch = _db.batch();
    final startDate = (data['date'] as Timestamp).toDate();

    for (int i = 1; i <= 3; i++) {
      final occurrenceDate = startDate.add(Duration(days: 7 * i));
      final ref = _db.collection('bookings').doc();

      batch.set(ref, {
        ...data,
        'status': 'accepted',
        'date': Timestamp.fromDate(occurrenceDate),
        'parentBookingId': parentId,
        'isAutoGenerated': true,
        'sessionNumber': i + 1,
      });
    }

    // Original booking = Session 1
    final parentRef = _db.collection('bookings').doc(parentId);
    batch.update(parentRef, {
      'sessionNumber': 1,
      'sessionsExpected': 4,
      'sessionsCompleted': 0,
    });

    await batch.commit();
  }

  // ---------- 4. TUTOR SESSIONS ----------
  Stream<List<Booking>> watchIncomingRequests() {
    return _db
        .collection('bookings')
        .where('tutorId', isEqualTo: _uid)
        .where('status', isEqualTo: 'pending')
        .orderBy('date')
        .snapshots()
        .map((q) => q.docs.map((doc) => Booking.fromDoc(doc)).toList());
  }

  Stream<List<Booking>> watchUpcomingSessions() {
    return _db
        .collection('bookings')
        .where('tutorId', isEqualTo: _uid)
        .where('status', isEqualTo: 'accepted')
        .orderBy('date')
        .snapshots()
        .map((q) => q.docs.map((doc) => Booking.fromDoc(doc)).toList());
  }

  Stream<List<Booking>> watchSessionHistory() {
    return _db
        .collection('bookings')
        .where('tutorId', isEqualTo: _uid)
        .where('status', whereIn: ['completed', 'declined', 'cancelled'])
        .orderBy('date', descending: true)
        .snapshots()
        .map((q) => q.docs.map((doc) => Booking.fromDoc(doc)).toList());
  }

  // ---------- 5. FEEDBACK ----------
  Stream<List<Review>> watchMyReviews() {
    return _db
        .collection('reviews')
        .where('tutorId', isEqualTo: _uid)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((q) => q.docs.map((doc) => Review.fromDoc(doc)).toList());
  }
// ---------- 6. MARK SESSION COMPLETED + RECORD EARNING ----------
Future<void> markSessionCompleted({
  required String bookingId,
}) async {
  final bookingRef = _db.collection('bookings').doc(bookingId);

  await _db.runTransaction((transaction) async {
    // ------------------------------------------------------------
    // GET BOOKING FIRST
    // ------------------------------------------------------------

    final bookingSnap = await transaction.get(bookingRef);

    if (!bookingSnap.exists) {
      throw Exception('Booking not found.');
    }

    final bookingData = bookingSnap.data()!;
    final currentStatus = bookingData['status'] ?? '';

    if (currentStatus == 'completed') {
      throw Exception('This session is already completed.');
    }

    if (currentStatus != 'accepted') {
      throw Exception(
        'Only an accepted session can be marked as completed.',
      );
    }

    final paymentType =
        bookingData['paymentType'] ?? PaymentType.none.name;

    final amount =
        (bookingData['amount'] ?? 0).toDouble();

    final contractId =
        bookingData['contractId'] as String?;

    // ------------------------------------------------------------
    // GET CONTRACT BEFORE ANY WRITES
    // ------------------------------------------------------------

    DocumentSnapshot<Map<String, dynamic>>? contractSnap;

    if (paymentType == PaymentType.monthlyContract.name) {
      if (contractId == null || contractId.isEmpty) {
        throw Exception(
          'Monthly contract ID is missing.',
        );
      }

      final contractRef =
          _db.collection('contracts').doc(contractId);

      contractSnap = await transaction.get(contractRef);

      if (!contractSnap.exists) {
        throw Exception(
          'Monthly contract not found.',
        );
      }
    }

    // ------------------------------------------------------------
    // MARK BOOKING AS COMPLETED
    // ------------------------------------------------------------

    transaction.update(bookingRef, {
      'status': 'completed',
    });

    // ============================================================
    // 1. PER-SESSION PAYMENT
    // ============================================================

    if (paymentType == PaymentType.perSession.name &&
        amount > 0) {
      transaction.update(bookingRef, {
        'paymentStatus': PaymentStatus.paid.name,
      });

      final earningRef =
          _db.collection('transactions').doc();

      transaction.set(earningRef, {
        'bookingId': bookingId,
        'contractId': null,
        'studentId': bookingData['studentId'],
        'tutorId': bookingData['tutorId'],
        'subject': bookingData['subject'],
        'amount': amount,
        'paymentType': paymentType,
        'status': 'paid',
        'createdAt': FieldValue.serverTimestamp(),
      });

      return;
    }

    // ============================================================
    // 2. MONTHLY CONTRACT
    // ============================================================

    if (paymentType == PaymentType.monthlyContract.name) {
      final contractData = contractSnap!.data()!;

      final contractRef =
          _db.collection('contracts').doc(contractId);

      final completed =
          (contractData['sessionsCompleted'] ?? 0) as int;

      final expected =
          (contractData['sessionsExpected'] ?? 4) as int;

      final totalAmount =
          (contractData['totalAmount'] ?? 0).toDouble();

      final newCompleted =
          completed + 1;

      // ----------------------------------------------------------
      // MARK THIS SESSION AS PAID
      // ----------------------------------------------------------

      transaction.update(bookingRef, {
        'paymentStatus': PaymentStatus.paid.name,
      });

      // ----------------------------------------------------------
      // UPDATE CONTRACT PROGRESS
      // ----------------------------------------------------------

      transaction.update(contractRef, {
        'sessionsCompleted': newCompleted,
        'updatedAt': FieldValue.serverTimestamp(),
        'status': newCompleted >= expected
            ? 'completed'
            : 'active',
      });

      // ----------------------------------------------------------
      // CREATE ONE EARNING FOR THE WHOLE CONTRACT
      // ----------------------------------------------------------

      if (newCompleted >= expected &&
          totalAmount > 0) {
        final earningRef =
            _db.collection('transactions').doc(contractId);

        transaction.set(earningRef, {
  'bookingId': bookingId,
  'contractId': contractId,
  'studentId': contractData['studentId'],
  'studentName': contractData['studentName'],
  'tutorId': contractData['tutorId'],
  'subject': contractData['subject'],
  'amount': totalAmount,
  'paymentType': PaymentType.monthlyContract.name,
  'status': 'paid',
  'createdAt': FieldValue.serverTimestamp(),
});
      }

      return;
    }
  });
}

// ---------- 7. SET PAYMENT TERMS ----------
Future<void> setPaymentTerms({
  required String bookingId,
  required PaymentType paymentType,
  required double amount,
}) async {
  if (amount <= 0) {
    throw Exception('Payment amount must be greater than 0.');
  }

  final bookingRef = _db.collection('bookings').doc(bookingId);
  final bookingSnap = await bookingRef.get();

  if (!bookingSnap.exists) {
    throw Exception('Booking not found.');
  }

  final bookingData = bookingSnap.data()!;

  // ------------------------------------------------------------
  // PREVENT SETTING PAYMENT TERMS MULTIPLE TIMES
  // ------------------------------------------------------------

  final currentPaymentType =
      bookingData['paymentType'] as String?;

  final currentAmount =
      (bookingData['amount'] ?? 0).toDouble();

  if ((currentPaymentType != null &&
          currentPaymentType != PaymentType.none.name) ||
      currentAmount > 0) {
    throw Exception(
      'Payment terms have already been configured for this booking and cannot be changed.',
    );
  }

  // ============================================================
  // 1. PER SESSION PAYMENT
  // ============================================================

  if (paymentType == PaymentType.perSession) {
    await bookingRef.update({
      'paymentType': PaymentType.perSession.name,
      'paymentStatus': PaymentStatus.pending.name,
      'amount': amount,
      'sessionsExpected': 1,
      'sessionsCompleted': 0,
      'contractId': null,
      'contractStartDate': null,
      'contractEndDate': null,
    });

    return;
  }

  // ============================================================
  // 2. MONTHLY CONTRACT
  // ============================================================

  if (paymentType == PaymentType.monthlyContract) {
    final parentBookingId =
        bookingData['parentBookingId'] ?? bookingId;

    final parentRef =
        _db.collection('bookings').doc(parentBookingId);

    final parentSnap = await parentRef.get();

    if (!parentSnap.exists) {
      throw Exception(
        'Original booking for this contract was not found.',
      );
    }

    final parentData = parentSnap.data()!;

    // Extra protection against duplicate contracts.
    if ((parentData['contractId'] as String?)?.isNotEmpty ?? false) {
      throw Exception(
        'Payment terms have already been set for this monthly contract.',
      );
    }

    final startDate =
        (parentData['date'] as Timestamp).toDate();

    final endDate =
        startDate.add(const Duration(days: 28));

    final generatedSessions = await _db
        .collection('bookings')
        .where(
          'parentBookingId',
          isEqualTo: parentBookingId,
        )
        .get();

    final sessionRefs = <DocumentReference>[
      parentRef,
      ...generatedSessions.docs.map(
        (doc) => doc.reference,
      ),
    ];

    const sessionsExpected = 4;

    // ----------------------------------------------------------
    // CREATE MASTER CONTRACT
    // ----------------------------------------------------------

    final contractRef =
        _db.collection('contracts').doc();

    final contractId = contractRef.id;

    final batch = _db.batch();

    batch.set(contractRef, {
      'studentId': parentData['studentId'],
      'tutorId': parentData['tutorId'],
      'subject': parentData['subject'],
      'paymentType':
          PaymentType.monthlyContract.name,

      // IMPORTANT:
      // This is the TOTAL monthly contract amount.
      'totalAmount': amount,

      'sessionsExpected': sessionsExpected,
      'sessionsCompleted': 0,

      'startDate':
          Timestamp.fromDate(startDate),

      'endDate':
          Timestamp.fromDate(endDate),

      'status': 'active',

      'createdAt':
          FieldValue.serverTimestamp(),

      'updatedAt':
          FieldValue.serverTimestamp(),
    });

    // ----------------------------------------------------------
    // UPDATE ALL MONTHLY SESSIONS
    // ----------------------------------------------------------

    for (final sessionRef in sessionRefs) {
      batch.update(sessionRef, {
        'paymentType':
            PaymentType.monthlyContract.name,

        'paymentStatus':
            PaymentStatus.pending.name,

        // IMPORTANT:
        // Keep the TOTAL contract amount here.
        // markSessionCompleted() divides it by 4
        // when creating the actual earning transaction.
        'amount': amount,

        'contractId': contractId,

        'sessionsExpected': sessionsExpected,

        'contractStartDate':
            Timestamp.fromDate(startDate),

        'contractEndDate':
            Timestamp.fromDate(endDate),
      });
    }

    await batch.commit();
  }
}
}