import 'package:cloud_firestore/cloud_firestore.dart';

enum BookingStatus {
  pending,
  accepted,
  declined,
  completed,
  cancelled,
}

enum SessionType {
  runtime,
  monthly,
}

enum PaymentStatus {
  unpaid,
  pending,
  paid,
}

enum PaymentType {
  none,
  perSession,
  monthlyContract,
}

class Booking {
  final String id;

  final String studentId;
  final String studentName;

  final String tutorId;

  final String subject;

  final DateTime date;
  final String time;

  final SessionType sessionType;

  final BookingStatus status;

  final String studentMessage;
  final String tutorMessage;

  // ---------- PAYMENT ----------
  final PaymentStatus paymentStatus;
  final PaymentType paymentType;
  final double amount;

  // ---------- CONTRACT / SESSIONS ----------
  final int sessionsExpected;
  final int sessionsCompleted;
  final int sessionNumber;

  final DateTime? contractStartDate;
  final DateTime? contractEndDate;

  final String? contractId;
  final String? parentBookingId;
  final bool isAutoGenerated;

  Booking({
    required this.id,
    required this.studentId,
    required this.studentName,
    required this.tutorId,
    required this.subject,
    required this.date,
    required this.time,
    required this.sessionType,
    required this.status,
    this.studentMessage = '',
    this.tutorMessage = '',
    this.paymentStatus = PaymentStatus.unpaid,
    this.paymentType = PaymentType.none,
    this.amount = 0.0,
    this.sessionsExpected = 0,
    this.sessionsCompleted = 0,
    this.sessionNumber = 1,
    this.contractStartDate,
    this.contractEndDate,
    this.contractId,
    this.parentBookingId,
    this.isAutoGenerated = false,
  });

  factory Booking.fromDoc(DocumentSnapshot doc) {
    final map = doc.data() as Map<String, dynamic>;

    return Booking(
      id: doc.id,

      studentId: map['studentId'] ?? '',
      studentName: map['studentName'] ?? '',
      tutorId: map['tutorId'] ?? '',
      subject: map['subject'] ?? '',

      date: (map['date'] as Timestamp).toDate(),

      time: map['time'] ?? '',

      sessionType:
          map['sessionType'] == 'monthly'
              ? SessionType.monthly
              : SessionType.runtime,

      status: BookingStatus.values.firstWhere(
        (s) => s.name == map['status'],
        orElse: () => BookingStatus.pending,
      ),

      studentMessage: map['studentMessage'] ?? '',
      tutorMessage: map['tutorMessage'] ?? '',

      // ---------- PAYMENT ----------

      paymentStatus: PaymentStatus.values.firstWhere(
        (p) => p.name == map['paymentStatus'],
        orElse: () => PaymentStatus.unpaid,
      ),

      paymentType: _paymentTypeFromFirestore(
        map['paymentType'],
      ),

      amount: (map['amount'] ?? 0).toDouble(),

      // ---------- CONTRACT / SESSIONS ----------

      sessionsExpected: (map['sessionsExpected'] ?? 0) as int,

      sessionsCompleted: (map['sessionsCompleted'] ?? 0) as int,

      sessionNumber: (map['sessionNumber'] ?? 1) as int,

      contractStartDate: _timestampToDate(
        map['contractStartDate'],
      ),

      contractEndDate: _timestampToDate(
        map['contractEndDate'],
      ),

      contractId: map['contractId'],
      parentBookingId: map['parentBookingId'],
      isAutoGenerated: map['isAutoGenerated'] ?? false,
    );
  }

  static PaymentType _paymentTypeFromFirestore(
    dynamic value,
  ) {
    switch (value) {
      case 'perSession':
        return PaymentType.perSession;

      case 'monthlyContract':
        return PaymentType.monthlyContract;

      default:
        return PaymentType.none;
    }
  }

  static DateTime? _timestampToDate(
    dynamic value,
  ) {
    if (value is Timestamp) {
      return value.toDate();
    }

    return null;
  }
}