// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlj1JG9vrMYvK_eZqmrw8fXZUJxxBhYXk',
    appId: '1:17204797454:web:02f80cf49d910c87729c5f',
    messagingSenderId: '17204797454',
    projectId: 'tutorconnect-b208f',
    authDomain: 'tutorconnect-b208f.firebaseapp.com',
    storageBucket: 'tutorconnect-b208f.firebasestorage.app',
    measurementId: 'G-EQ9FCGGS9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWl6p8QBnLObMMUZgRCjH8i7_LPhKj8wU',
    appId: '1:17204797454:android:e84c84dbf6a5e691729c5f',
    messagingSenderId: '17204797454',
    projectId: 'tutorconnect-b208f',
    storageBucket: 'tutorconnect-b208f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnKOKaETAaThSr8w67ves81fDSmSPA1Ls',
    appId: '1:17204797454:ios:8407707f2a11814b729c5f',
    messagingSenderId: '17204797454',
    projectId: 'tutorconnect-b208f',
    storageBucket: 'tutorconnect-b208f.firebasestorage.app',
    iosBundleId: 'com.example.tutorConnect',
  );
}
